pipeline {

    agent { label "master" }


    parameters {
        choice(
                choices: ['testParallel', 'test'],
                description: 'Choose an execution type',
                name: 'Execution type'
        )
    }

    stages {

        stage('Maven build') {
            steps {
			    dir('KarateTechTalk') {
					sh "mvn clean"
				}
            }
        }
        stage('test') {
            steps {
			    dir('KarateTechTalk') {
					script {
						sh "mvn test -Dtest=ExamplesTest#${params.Environment}"
					}
				}
			}
		}
        stage('generate reports') {
            steps {
			    dir('KarateTechTalk') {
					cucumber buildStatus: "UNSTABLE",
					fileIncludePattern: "**/*.json",
					jsonReportDirectory: "target/karate-reports"
				}
			}
		}
    }

}
